#!/usr/bin/env bash
#
# man git-daemon(1) --access-hook
#

REQUEST_PATH="$2"

case "$(basename $REQUEST_PATH)" in
james)
    case "$REMOTE_ADDR" in
    127.0.0.1) true ;;
    10.0.2.*)  true ;;
    10.0.1.*) true ;;
    *) false ;;
    esac
;;
*)
    echo "Access denied"
    return 1
;;
esac
