[env]
# The git information to use in commits from kage-core
KAGE_GIT_EMAIL = "kafva.one"
KAGE_GIT_REMOTE = "origin"
KAGE_GIT_BRANCH = "main"

# Unit test variables
KAGE_TEST_GIT_REPONAME = "james.git"
KAGE_TEST_GIT_REMOTE_CLONE_URL = "git://127.0.0.1"
KAGE_TEST_GIT_CLIENT_DIR = "../.testenv/kage-client"
