#!/usr/bin/env bash
#
# man git-daemon(1) --access-hook
#

REQUEST_PATH="$2"

case "$(basename $REQUEST_PATH)" in
james.git)
    [ "$REMOTE_ADDR" = 127.0.0.1 ]
;;
*_test) # Unit tests
    case "$REMOTE_ADDR" in
    127.0.0.1) exit 0 ;;
    *)         exit 1 ;;
    esac
;;
*)
    echo "Access denied"
    exit 1
;;
esac
