#!/usr/bin/env bash
set -e

TAG=$(git describe --tags)

echo "Building tag: $TAG"

make -C core clean
ANDROID_TARGET_ARCH=aarch64 make -C core android
ANDROID_TARGET_ARCH=x86_64 make -C core android

export JAVA_HOME=/opt/homebrew/opt/openjdk@21
(cd android && ./gradlew setVersion)
(cd android && ./gradlew build assembleRelease)

echo "Checking version strings"
set -x
grep -q "version = \"${TAG##v}\"" core/Cargo.toml
grep -q "version = \"${TAG##v}\"" core/Cargo.lock
grep -q "MARKETING_VERSION = ${TAG##v}" ios/kage.xcodeproj/project.pbxproj
grep -q "versionName = \"${TAG##v}\"" android/build.gradle.kts
grep -q "$TAG" android/src/main/res/values/version.xml

gh release create $TAG android/build/outputs/apk/release/kage-release.apk
