#!/usr/bin/env bash
set -e

echox () { echo "+ $*" && $@; }

TAG=$(git describe --tags)

echo "Building tag: $TAG"

make -C core clean
ANDROID_TARGET_ARCH=aarch64 make -C core android
ANDROID_TARGET_ARCH=x86_64 make -C core android

export JAVA_HOME=/opt/homebrew/opt/openjdk@21
fd version.xml android -x cat {}

(cd android && ./gradlew build assembleRelease)

echox gh release create $TAG android/build/outputs/apk/release/kage-release.apk
