/**
 * https://material-foundation.github.io/material-theme-builder/
 */
package one.kafva.kage.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF334C96)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF5A71BD)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF555D7C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD7DEFF)
val onSecondaryContainerLight = Color(0xFF3D4562)
val tertiaryLight = Color(0xFF29438D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF5068B4)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFFF3343)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF1A1B20)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF1A1B20)
val surfaceVariantLight = Color(0xFFE1E1EF)
val onSurfaceVariantLight = Color(0xFF444651)
val outlineLight = Color(0xFF757682)
val outlineVariantLight = Color(0xFFC5C6D3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3035)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFB5C4FF)
val surfaceDimLight = Color(0xFFDAD9E0)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3FA)
val surfaceContainerLight = Color(0xFFEFEDF4)
val surfaceContainerHighLight = Color(0xFFE9E7EE)
val surfaceContainerHighestLight = Color(0xFFE3E1E9)

val primaryDark = Color(0xFFB5C4FF)
val onPrimaryDark = Color(0xFF0B2A74)
val primaryContainerDark = Color(0xFF5A71BD)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFBDC5E9)
val onSecondaryDark = Color(0xFF272F4B)
val secondaryContainerDark = Color(0xFF373F5C)
val onSecondaryContainerDark = Color(0xFFCCD3F8)
val tertiaryDark = Color(0xFFB5C4FF)
val onTertiaryDark = Color(0xFF0A2A74)
val tertiaryContainerDark = Color(0xFF354E98)
val onTertiaryContainerDark = Color(0xFFF3F3FF)
val errorDark = Color(0xFFFFFFFF)
val onErrorDark = Color(0xFF81080E)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121318)
val onBackgroundDark = Color(0xFFE3E1E9)
val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFE3E1E9)
val surfaceVariantDark = Color(0xFF444651)
val onSurfaceVariantDark = Color(0xFFC5C6D3)
val outlineDark = Color(0xFF8F909C)
val outlineVariantDark = Color(0xFF444651)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E1E9)
val inverseOnSurfaceDark = Color(0xFF2F3035)
val inversePrimaryDark = Color(0xFF435AA5)
val surfaceDimDark = Color(0xFF121318)
val surfaceBrightDark = Color(0xFF38393E)
val surfaceContainerLowestDark = Color(0xFF0D0E13)
val surfaceContainerLowDark = Color(0xFF1A1B20)
val surfaceContainerDark = Color(0xFF1E1F24)
val surfaceContainerHighDark = Color(0xFF292A2F)
val surfaceContainerHighestDark = Color(0xFF34343A)
